apiVersion: v1
kind: ConfigMap
metadata:
  name: pbs-redirector
  namespace: pbs-redirector
data:
  caddyfile: |
    {
        email itkom@pbs.ch
        acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
    }
    thilo.scout.ch:80 {
        redir https://thilo.scouts.ch{uri} permanent
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pbs-redirector
  namespace: pbs-redirector
spec:
  rules:
    - host: thilo.scout.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pbs-redirector
                port:
                  number: 80
  tls:
    - hosts:
        - thilo.scout.ch
---
apiVersion: v1
kind: Service
metadata:
  name: pbs-redirector
  namespace: pbs-redirector
spec:
  selector:
    name: pbs-redirector
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pbs-redirector-config
  namespace: pbs-redirector
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: csi-cinder-sc-delete
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pbs-redirector-data
  namespace: pbs-redirector
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: csi-cinder-sc-delete
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbs-redirector
  namespace: pbs-redirector
spec:
  selector:
    matchLabels:
      name: pbs-redirector
  template:
    metadata:
      labels:
        name: pbs-redirector
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      containers:
        - name: pbs-redirector
          image: caddy:2.10.2@sha256:dedfbbeb703b2ce9ff4a98fc06aa9c7c7d9a42f0b7d778738c1dd3ef11dcc767
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: caddyfile
            - name: pbs-redirector-config
              mountPath: /config
            - name: pbs-redirector-data
              mountPath: /data
      volumes:
        - name: caddyfile
          configMap:
            name: pbs-redirector
        - name: pbs-redirector-config
          persistentVolumeClaim:
            claimName: pbs-redirector-config
        - name: pbs-redirector-data
          persistentVolumeClaim:
            claimName: pbs-redirector-data
