---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: pbs-redirector
  namespace: pbs-redirector
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: traefik
  # Only Routes from the same namespace are allowed.
  listeners:
    # optional, only if you want to expose port 80 directly.
    - name: http
      protocol: HTTP
      port: 8000 # Default traefik helm chart port, will be mapped to 80
      hostname: thilo.scout.ch
      allowedRoutes:
        namespaces:
          from: Same

    - name: https
      protocol: HTTPS
      port: 8443 # Default traefik helm chart port, will be mapped to 443
      hostname: thilo.scout.ch
      tls:
        mode: Terminate
        certificateRefs:
          - name: secret-tls
            namespace: pbs-redirector

      allowedRoutes:
        namespaces:
          from: Same
---
# Optional, this is by default already configured on the ingress setup. But we keep it here as example if you wanna expose something without certificate
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pbs-redirector-http
  namespace: pbs-redirector
spec:
  hostnames:
    - thilo.scout.ch
  parentRefs:
    - name: pbs-redirector
      sectionName: http
      kind: Gateway
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: thilo.scouts.ch
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pbs-redirector-https
  namespace: pbs-redirector
spec:
  hostnames:
    - thilo.scout.ch
  parentRefs:
    - name: pbs-redirector
      sectionName: https
      kind: Gateway
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: thilo.scouts.ch
            statusCode: 301
